config/routes.rb
# == Route Map
#
#                                 Prefix Verb   URI Pattern                                                       Controller#Action
#                       new_user_session GET    /users/sign_in(.:format)                                          devise/sessions#new
#                           user_session POST   /users/sign_in(.:format)                                          devise/sessions#create
#                   destroy_user_session DELETE /users/sign_out(.:format)                                         devise/sessions#destroy
#                      new_user_password GET    /users/password/new(.:format)                                     devise/passwords#new
#                     edit_user_password GET    /users/password/edit(.:format)                                    devise/passwords#edit
#                          user_password PATCH  /users/password(.:format)                                         devise/passwords#update
#                                        PUT    /users/password(.:format)                                         devise/passwords#update
#                                        POST   /users/password(.:format)                                         devise/passwords#create
#                               ckeditor        /ckeditor                                                         Ckeditor::Engine
#                            sidekiq_web        /sidekiq                                                          Sidekiq::Web
#                             live_event GET    /events/:id/live(.:format)                                        events#live
#                         validate_event GET    /events/:id/validate(.:format)                                    events#validate
#                           ticket_event GET    /events/:id/ticket(.:format)                                      events#ticket
#                       mailtester_event GET    /events/:id/mailtester(.:format)                                  events#mailtester
#                    do_mailtester_event POST   /events/:id/do_mailtester(.:format)                               events#do_mailtester
#                       print_list_event GET    /events/:id/print_list(.:format)                                  events#print_list
#                          checkin_event GET    /events/:id/checkin(.:format)                                     events#checkin
#                 send_invitations_event POST   /events/:id/send_invitations(.:format)                            events#send_invitations
#         check_invitations_status_event POST   /events/:id/check_invitations_status(.:format)                    events#check_invitations_status
#                   send_test_mail_event POST   /events/:id/send_test_mail(.:format)                              events#send_test_mail
#                       import_csv_event GET    /events/:id/import_csv(.:format)                                  events#import_csv
#                       export_csv_event GET    /events/:id/export_csv(.:format)                                  events#export_csv
#                    export_failed_event GET    /events/:id/export_failed(.:format)                               events#export_failed
#                    do_import_csv_event POST   /events/:id/do_import_csv(.:format)                               events#do_import_csv
#         send_invitation_event_attendee POST   /events/:event_id/attendees/:id/send_invitation(.:format)         attendees#send_invitation
# check_invitation_status_event_attendee POST   /events/:event_id/attendees/:id/check_invitation_status(.:format) attendees#check_invitation_status
#                  ticket_event_attendee GET    /events/:event_id/attendees/:id/ticket(.:format)                  attendees#ticket
#                    logs_event_attendee GET    /events/:event_id/attendees/:id/logs(.:format)                    attendees#logs
#                 checkin_event_attendee GET    /events/:event_id/attendees/:id/checkin(.:format)                 attendees#checkin
#                        event_attendees GET    /events/:event_id/attendees(.:format)                             attendees#index
#                                        POST   /events/:event_id/attendees(.:format)                             attendees#create
#                     new_event_attendee GET    /events/:event_id/attendees/new(.:format)                         attendees#new
#                    edit_event_attendee GET    /events/:event_id/attendees/:id/edit(.:format)                    attendees#edit
#                         event_attendee GET    /events/:event_id/attendees/:id(.:format)                         attendees#show
#                                        PATCH  /events/:event_id/attendees/:id(.:format)                         attendees#update
#                                        PUT    /events/:event_id/attendees/:id(.:format)                         attendees#update
#                                        DELETE /events/:event_id/attendees/:id(.:format)                         attendees#destroy
#                       event_categories GET    /events/:event_id/categories(.:format)                            categories#index
#                                        POST   /events/:event_id/categories(.:format)                            categories#create
#                     new_event_category GET    /events/:event_id/categories/new(.:format)                        categories#new
#                    edit_event_category GET    /events/:event_id/categories/:id/edit(.:format)                   categories#edit
#                         event_category GET    /events/:event_id/categories/:id(.:format)                        categories#show
#                                        PATCH  /events/:event_id/categories/:id(.:format)                        categories#update
#                                        PUT    /events/:event_id/categories/:id(.:format)                        categories#update
#                                        DELETE /events/:event_id/categories/:id(.:format)                        categories#destroy
#                                 events GET    /events(.:format)                                                 events#index
#                                        POST   /events(.:format)                                                 events#create
#                              new_event GET    /events/new(.:format)                                             events#new
#                             edit_event GET    /events/:id/edit(.:format)                                        events#edit
#                                  event GET    /events/:id(.:format)                                             events#show
#                                        PATCH  /events/:id(.:format)                                             events#update
#                                        PUT    /events/:id(.:format)                                             events#update
#                                        DELETE /events/:id(.:format)                                             events#destroy
#                           mg_delivered POST   /mg/delivered(.:format)                                           mg#webhook
#                             mg_dropped POST   /mg/dropped(.:format)                                             mg#webhook
#                             mg_bounced POST   /mg/bounced(.:format)                                             mg#webhook
#                                  users GET    /users(.:format)                                                  users#index
#                                        POST   /users(.:format)                                                  users#create
#                               new_user GET    /users/new(.:format)                                              users#new
#                              edit_user GET    /users/:id/edit(.:format)                                         users#edit
#                                   user GET    /users/:id(.:format)                                              users#show
#                                        PATCH  /users/:id(.:format)                                              users#update
#                                        PUT    /users/:id(.:format)                                              users#update
#                                        DELETE /users/:id(.:format)                                              users#destroy
#                                   root GET    /                                                                 static#index
#                          configuration GET    /configuration(.:format)                                          static#configuration
#                       example_validate GET    /example_validate(.:format)                                       static#example_validate
#
# Routes for Ckeditor::Engine:
#         pictures GET    /pictures(.:format)             ckeditor/pictures#index
#                  POST   /pictures(.:format)             ckeditor/pictures#create
#          picture DELETE /pictures/:id(.:format)         ckeditor/pictures#destroy
# attachment_files GET    /attachment_files(.:format)     ckeditor/attachment_files#index
#                  POST   /attachment_files(.:format)     ckeditor/attachment_files#create
#  attachment_file DELETE /attachment_files/:id(.:format) ckeditor/attachment_files#destroy
#

Rails.application.routes.draw do
  devise_for :users, skip: [:registration]

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :events do
    member do
      get 'live', as: 'live'
      get 'validate', as: 'validate'
      get 'ticket', as: 'ticket'

      get 'mailtester', as: 'mailtester'
      post 'do_mailtester', as: 'do_mailtester'

      get 'print_list', as: 'print_list'
      get 'checkin', as: 'checkin'

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  model              :text
#  start              :datetime
#  end                :datetime
#  venue              :string
#  subject            :string
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Event < ApplicationRecord
  has_many :attendees
  has_many :categories

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/noimagefound.jpg'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, uniqueness: true
  validates :start, :venue, presence: true

  def tag
    "Event-#{id}"
  end

  def self.dummy
    event = Event.new
    event.name = 'Fête nationale'
    event.venue = 'Residence de France'
    event.start = '2017-07-14 12:30'
    event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:validate]
  skip_after_action :verify_authorized, only: [:validate]

  # GET /events
  # GET /events.json
  def index
    authorize Event
    @events = Event.order(start: :desc).page params[:page]
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize @event
  end

  # GET /events/new
  def new
    authorize Event
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  # POST /events.json
  def create
    authorize Event
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_invitations_status
    event = Event.find params[:id]

    authorize event

    CheckInvitationsStatusJob.perform_later(params[:id])

    redirect_to event_attendees_path(params[:id]), notice: 'Invitations status checking in progress'
  end

  def send_invitations
    event = Event.find params[:id]

    authorize event

    attendees = event.attendees.where(mailgun_id: nil)

    attendees.each do |attendee|
      SendInvitationJob.perform_later(event.id, attendee.id)
    end

    redirect_to event_attendees_path(params[:id]), notice: "#{attendees.count} invitations queued"
  end

  def checkin
    @event = Event.find params[:id]
    authorize @event
  end

  def print_list
    @event = Event.find params[:id]
    authorize @event
    render layout: false
  end

  def do_mailtester
    event = Event.find params[:id]
    authorize event

    attendee = Attendee.dummy
    to = "#{ENV['MAILTESTER_LOGIN']}-Event#{event.id}@mail-tester.com"

    MailGeneratorService.new(event: event, attendee: attendee, to: to).generate_and_send_now

    redirect_to mailtester_event_path(params[:id]), notice: 'Mail sent to mailtester for testing'
  end

  def send_test_mail
    event = Event.find params[:id]
    authorize event
    email = params[:email]

    attendee = Attendee.dummy

    MailGeneratorService.new(event: event, attendee: attendee, to: email).generate_and_send_now

    redirect_to event, notice: "Test mail sent to #{email}"
  end

  def import_csv
    @event = Event.find params[:id]
    authorize @event
  end

  def export_csv
    @event = Event.find params[:id]
    authorize @event

    columns = [:first_name, :last_name, :email, :reference, :category, :checkin_at]

    @csv = CSV.generate do |csv|
      csv << columns
      @event.attendees.each do |attendee|
        csv << [attendee.first_name, attendee.last_name, attendee.reference, attendee.email, attendee.category.name, attendee.checkin_at]
      end
    end

    send_data @csv, filename: 'export.csv'
  end

  def export_failed
    @event = Event.find params[:id]
    authorize @event

    @failed = @event.attendees.select("attendees.first_name, attendees.last_name, attendees.email, attendees.category_id, logs.json->'delivery-status'->>'message' as message, logs.json->'delivery-status'->>'description' as description").joins(:logs).where("cast(logs.json->>'timestamp' as float) = (select max(cast(json->>'timestamp' as float)) from logs where attendee_id = attendees.id)").where("logs.json->>'event' = ?", 'failed').where("logs.json->>'severity' = ?", 'permanent')

    columns = [:first_name, :last_name, :email, :category, :message, :description]

    @csv = CSV.generate do |csv|
      csv << columns
      @failed.each do |attendee|
        csv << [attendee.first_name, attendee.last_name, attendee.email, attendee.category.name, attendee.message, attendee.description]
      end
    end

    send_data @csv, filename: 'export_failed.csv'
  end

  def do_import_csv
    @event = Event.find params[:id]
    authorize @event

    @category = Category.find params[:category_id]
    @send_invites = params[:send_invites] == '1'

    csv_importer = CsvImporterService.new(file: params[:file], event_id: params[:id], category_id: params[:category_id], send_invites: params[:send_invites] == '1')

    begin
      count = csv_importer.import
      redirect_to event_attendees_path(params[:id]), notice: "#{count} attendees added"
    rescue Exception => e
      flash[:error] = "#{e.class} - #{e.message}"
      render :import_csv
    end
  end

  def mailtester
    @event = Event.find params[:id]
    authorize @event

    @result = MailtesterService.new(event: @event).result
  end

  def validate
    @event = Event.find params[:id]
    @attendee = @event.attendees.where(reference: params[:ref]).first

    ticket_validator = TicketValidatorService.new(event: @event, attendee: @attendee)
    ticket_validator.validate

    @is_valid = ticket_validator.is_valid?
    @message = ticket_validator.message

    render layout: false
  end

  def ticket
    authorize Event
    code = params[:code]

    @attendee = Attendee.dummy

    @qrcode = RQRCode::QRCode.new("http://attendize.ambafrance.co/example_validate?ref=#{code}")
    render 'attendees/ticket', layout: false, locals: { attendee: @attendee, event: @attendee.event, qrcode: @qrcode }
  end

  def live
    @event = Event.find params[:id]
    authorize @event

    @checkedin = @event.attendees.where.not(checkin_at: nil).count
    @total = @event.attendees.count
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :subject, :model, :start, :end, :venue, :image)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_menu.html.erb
<div class="row">
	<div class="col">
		<ul class="nav nav-pills justify-content-center">
		  <li class="nav-item">
			  <%= link_to 'Detail', event_path(event), class: ['nav-link', if current_page?(event_path(event)) then 'active' end] %>
		  </li>
		  <li class="nav-item">
			  <%= link_to 'Categories', event_categories_path(event), class: ['nav-link', if current_page?(event_categories_path(event)) then 'active' end] %>
		  </li>
		  <li class="nav-item">
			  <%= link_to 'Attendees', event_attendees_path(event), class: ['nav-link', if current_page?(event_attendees_path(event)) then 'active' end] %>
		  </li>
		  <li class="nav-item">
			  <%= link_to 'Mailtester', mailtester_event_path(event), class: ['nav-link', if current_page?(mailtester_event_path(event)) then 'active' end] %>
		  </li>
		</ul>
	</div>
</div>

app/views/events/checkin.html.erb
<%= link_to 'Success ticket', ticket_event_path(code: "VALID") %>
<%= link_to 'Already checked in ticket', ticket_event_path(code: "ALRDY") %>
<%= link_to 'Before event ticket', ticket_event_path(code: "BEFORE") %>
<%= link_to 'Not invited ticket', ticket_event_path(code: "NOTINV") %>

<h1>iPhone</h1>

<%= image_tag 'docs/iphone/app_store.png' %>
<%= image_tag 'docs/iphone/config.png' %>
<%= image_tag 'docs/iphone/scan.png' %>
<%= image_tag 'docs/iphone/result.png' %>

<h1>Android</h1>

<%= image_tag 'docs/android/play_store.png' %>
<%= image_tag 'docs/android/config.png' %>
<%= image_tag 'docs/android/scan.png' %>
<%= image_tag 'docs/android/result.png' %>

app/views/events/checkin_scan.html.erb
<!doctype html>
<html>
<head>
    <title>
	    <%= @event.name %>
    </title>
    <%= javascript_include_tag 'application' %>
</head>
<body>

	<video id="preview" width="100%" height="100%"></video>
    <script type="text/javascript">
      scanner = new Instascan.Scanner({ video: document.getElementById('preview') , mirror: false });
      scanner.addListener('scan', function (content) {
        alert(content);
      });
      Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
          scanner.start(cameras[1]);
        } else {
          alert('No cameras found.');
        }
      }).catch(function (e) {
        alert(e);
      });
    </script>
</body>
</html>

<!-- nativa :


<!DOCTYPE html>
<html>
  <head>
    <title>title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
.mirror {
  transform: scaleX(-1);
}
</style>
  </head>
  <body>
    <video id="video" autoplay ></video>
    <canvas id="canvas" style="display:none" ></canvas>
  <script type="text/javascript">
var barcodeDetector = new BarcodeDetector();
var video = document.getElementById('video');
var canvas = document.getElementById('canvas');
var ctx = canvas.getContext("2d");

var running = false;

  function decode() {

    if (!running) {
    
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    image = ctx.getImageData(0, 0, canvas.width, canvas.height);

    barcodeDetector.detect(image)
        .then(barcodes => {
              running = false;
              barcodes.forEach(barcode => alert(barcode.rawValue))
                  })
      .catch((e) => {
                running = false;
                alert("Boo, BarcodeDetection failed: " + e);
              });

      running = true;
    }

    setInterval(decode, 2000);

  }
  
  document.addEventListener('DOMContentLoaded', function() {

    video.addEventListener('play', function() {
      w = video.videoWidth;
      h = video.videoHeight;

      canvas.width = w; canvas.height = h;

      setInterval(decode, 2000);
    });

    navigator.getUserMedia({video: { facingMode: "environment" }}, 
      function(stream) {
         video.src = window.URL.createObjectURL(stream);
      },
      function(err) {
         alert("The following error occurred: " + err.name);
      }
   );


  });

  </script>
  </body>
</html>

-->

app/views/events/edit.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title">Editing event</h4>
    <%= simple_form_for @event do |f| %>
	    <%= f.input :name %>
	    <%= f.input :venue %>
	    <%= f.input :start, as: :string %>
	    <%= f.input :end, as: :string %>
	    <%= f.input :image %>
	    <hr/>
	    <%= f.input :subject %>

	<div class="card card-inverse card-info mb-3">
		<div class="card-block">
			<blockquote class="card-blockquote">
				<p>Merge fields:</p>
				<ul>
					<li><code>{{first_name}}</code>: First name of the attendee</li>
					<li><code>{{last_name}}</code>: Last name of the attendee</li>
					<li><code>{{full_name}}</code>: Full name of the attendee</li>
				</ul>
			</blockquote>
		</div>
	</div>	

	    <%= f.input :model, as: :ckeditor %>
      <div class="text-right">
	    <%= link_to 'Cancel', event_path, class: "btn btn-outline-danger btn-lg" %>
	    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">

$('#event_start').datetimepicker({step: 15, minDate: 0});
$('#event_end').datetimepicker({step: 15, minDate: 0});

</script>

app/views/events/import_csv.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title">Import csv</h4>
	<%= form_tag do_import_csv_event_path, method: :post, multipart: true do %>
		<div class="form-group">
			<label class="control-label" for="attendee_first_name">
				<abbr title="required">*</abbr> File</label>
			  <%= file_field_tag :file, class: "form-control" %>
		</div>
		<div class="form-group">
			<label class="control-label" for="attendee_category_id">
				<abbr title="required">*</abbr> Category</label>
			<%= select_tag :category_id, options_from_collection_for_select(@event.categories, "id", "name"), include_blank: true %>
		</div>
		<div class="form-group">
			<div class="checkbox">
				<label class="boolean optional" for="attendee_send_invite">
					<%= check_box_tag :send_invites, 1, true %>
					Send invite
				</label>
			</div>
		</div>
      <div class="text-right">
	  <%= link_to 'Cancel', event_attendees_path(@event), class: "btn btn-outline-danger btn-lg" %>
	  <%= submit_tag :import, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
	<div class="col-2">

		<div class="card">
			<%= image_tag 'events.png', class: "card-img-top", style: "margin: 10px auto 10px auto; max-width: 100%" %>
			<div class="card-block">

				<hr/>
				<%= link_to 'Add event', new_event_path, class: "btn btn-primary btn-block" %>
			</div>
		</div>

	</div>
	<div class="col">
		<h1>Events</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Start</th>
					<th>Where</th>
					<th>Attendees count</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @events.each do |event| %>
					<tr>
						<td><%= event.name %></td>
						<td><%= event.venue %></td>
						<td><%= event.start.strftime("%B %d at %I:%M %p") %></td>
						<td><%= event.attendees.count %></td>
						<td>
							<%= link_to event, class: "btn btn-outline-primary btn-sm" do %>
								<i class="fa fa-cog" aria-hidden="true"></i> Manage
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<%= paginate @events %>

	</div>

</div>

app/views/events/live.html.erb
<%= @checkedin %> / <%= @total %> (<%= (@checkedin / (@total+0.0)*100).round(2) %> %)

<div id="container"></div>

  <script type="text/javascript">


  Highcharts.chart('container', {
    chart: {
        type: 'bar'
    },
    title: {
        text: 'Checked in attendees'
    },
    xAxis: {
        categories: <%= raw @event.categories.pluck(:name).to_s %>,
        title: {
            text: null
        }
    },
    yAxis: {
        min: 0,
      allowDecimals: false,
        title: {
          text: null
        }
    },
    plotOptions: {
        bar: {
            animation: false,
            dataLabels: {
                enabled: true
            }
        }
    },
    legend: {
      enabled: false
    },
    credits: {
        enabled: false
    },
    series: [
    {
      data: <%= raw @event.categories.map { |c| c.attendees.where.not(checkin_at: nil).count }.to_s %>
    },
    ]
});

  </script>

 <script type="text/javascript">
setInterval(function() {
    window.location.reload();
}, 120000); 
 </script>

app/views/events/mailtester.html.erb
<%= render 'menu', event: @event %>

<div class="row mt-3">
	<div class="col-2">


		<div class="card">
		  <%= image_tag @event.image.url(:thumb), class: "card-img-top", style: "margin: 10px auto 10px auto; max-width: 100%"  %>
		  <div class="card-block">

			<%= link_to "https://www.mail-tester.com/#{@result['mailboxId']}", target: "_blank", class: "btn btn-secondary btn-block" do %>
				<i class="fa fa-external-link" aria-hidden="true"></i> View results
			<% end %>
			<hr/>
			<%= link_to "Run the test", do_mailtester_event_path, method: :post, class: "btn btn-primary btn-block" %>
		  </div>
		</div>

	</div>
	<div class="col">
		<%= image_tag 'logos/mailtester.png', style: "max-height: 50px" %>

		<% if @result['status'] %>
			<% klass = case 10+@result['mark']; when 6..10; then 'success'; when 5..6; then 'warning'; else 'danger' end %>
			<div class="card card-inverse card-<%= klass %> mt-3 text-center">
		  <div class="card-block">
		    <blockquote class="card-blockquote">
			    <p><%= @result['title'] %></p>
			    <p class="mb-0" style="font-size: 30px; font-weight: bold"><%= @result['displayedMark'] %></p>
		    </blockquote>
		  </div>
		</div>

		<div class="json mt-3" id="render">
		</div>

		<script type="text/javascript">

		formatter = new JSONFormatter(<%= raw @result.to_json %>);
		div = document.getElementById('render');
		div.innerHTML = '';
		div.appendChild(formatter.render());

		</script>
		<% else %>
		    <div class="card card-outline-primary my-3 text-center">
		      <div class="card-block">
			<blockquote class="card-blockquote">
			  <p>The test hasn't been run</p>
			  <%= link_to 'Run the test', do_mailtester_event_path, method: :post, class: "btn btn-primary" %>
			</blockquote>
		      </div>
		    </div>
		<% end %>
	</div>
</div>

app/views/events/new.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title">New event</h4>
    <%= simple_form_for @event do |f| %>
	    <%= f.input :name %>
	    <%= f.input :venue %>
	    <%= f.input :start, as: :string %>
	    <%= f.input :end, as: :string %>
      <div class="text-right">
        <%= link_to 'Cancel', :root, class: "btn btn-outline-danger btn-lg" %>
        <%= f.button :submit, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $('#event_start').datetimepicker({step: 15, minDate: 0});
    $('#event_end').datetimepicker({step: 15, minDate: 0});
</script>

app/views/events/show.html.erb
<%= render 'menu', event: @event %>

<div class="row mt-3">
	<div class="col-2">


		<div class="card">
		  <%= image_tag @event.image.url(:thumb), class: "card-img-top", style: "margin: 10px auto 10px auto; max-width: 100%" %>
		  <div class="card-block">

			<%= link_to print_list_event_path, class: "btn btn-secondary btn-block" do %>
				<i class="fa fa-print" aria-hidden="true"></i> Print list
			<% end %>

			<%= link_to checkin_event_path, class: "btn btn-secondary btn-block" do %>
				<i class="fa fa-qrcode" aria-hidden="true"></i> Check-in
			<% end %>

			<%= link_to live_event_path, class: "btn btn-secondary btn-block" do %>
				<i class="fa fa-play" aria-hidden="true"></i> Live
			<% end %>
			<hr/>
			<%= link_to 'Edit', edit_event_path, class: "btn btn-primary btn-block" %>
		  </div>
		</div>

	</div>
	<div class="col">
		<h1>Event details</h1>
		<table class="table table-striped">
			<tbody>
				<tr><th>Name</th><td><%= @event.name %></td></tr>
				<tr><th>Venue</th><td><%= @event.venue %></td></tr>
				<tr><th>Start</th><td><%= @event.start.strftime("%B %d at %I:%M %p") %></td></tr>
				<tr><th>End</th><td><%= @event.end.strftime("%B %d at %I:%M %p") if @event.end %></td></tr>
			</tbody>
		</table>

		<hr class="mt-5" />
		<h5><%= @event.subject %></h5>
		<hr/>
		<div class="media">
			<%= image_tag 'profile_mask2.png', class: 'd-flex mr-3', style: "background-color: #ccc" %>
		  <div class="media-body">
			  <span class="mt-0"><span style="color: #222; font-weight: bold" ><%= ENV['MAILGUN_SENDER_NAME'] %></span> <span style="color: #777"><%= ENV['MAILGUN_SENDER_EMAIL'] %> <span style="text-decoration: underline; color: #222">via</span> <%= ENV['MAILGUN_DOMAIN'] %></span><br/>
			  <span class="mt-0" style="color: #777" >to me</span>
		  </div>
		</div>
		<hr/>
		<%= raw @event.model %>

		<hr/>

		<%= form_tag send_test_mail_event_path, method: :post do %>

			<%= text_field_tag :email %>
			<%= submit_tag 'Send test mail' %>

		<% end %>
	</div>
</div>

app/views/events/validate.html.erb
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <title>Attendize</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
<style>

body {
	background-color: <% if @is_valid %>#1fa67a<% else %>#a61f4b<% end %>;
}

.content {
	height: 85%;
	display: flex;
	align-items: center;
	justify-content: center;
	padding-top: 5%;
}

.inner {
	text-align: center;
}

</style>
</head>
<body>
	<div class="content">
		<div class="inner">
			<% if @is_valid %>
				<%= image_tag 'checkin_ok.png' %>
			<% else %>
				<%= image_tag 'checkin_ko.png' %>
			<% end%>

			<% if @attendee %>
				<p><%= @attendee.full_name %></p>
				<p><%= @attendee.category.name %></p>
			<% end %>

			<p><%= @message %></p>
		</div>
	</div>
</body>
</html>