config/routes.rb
# == Route Map
#
#                                 Prefix Verb   URI Pattern                                                       Controller#Action
#                       new_user_session GET    /users/sign_in(.:format)                                          devise/sessions#new
#                           user_session POST   /users/sign_in(.:format)                                          devise/sessions#create
#                   destroy_user_session DELETE /users/sign_out(.:format)                                         devise/sessions#destroy
#                      new_user_password GET    /users/password/new(.:format)                                     devise/passwords#new
#                     edit_user_password GET    /users/password/edit(.:format)                                    devise/passwords#edit
#                          user_password PATCH  /users/password(.:format)                                         devise/passwords#update
#                                        PUT    /users/password(.:format)                                         devise/passwords#update
#                                        POST   /users/password(.:format)                                         devise/passwords#create
#                               ckeditor        /ckeditor                                                         Ckeditor::Engine
#                            sidekiq_web        /sidekiq                                                          Sidekiq::Web
#                             live_event GET    /events/:id/live(.:format)                                        events#live
#                         validate_event GET    /events/:id/validate(.:format)                                    events#validate
#                           ticket_event GET    /events/:id/ticket(.:format)                                      events#ticket
#                       mailtester_event GET    /events/:id/mailtester(.:format)                                  events#mailtester
#                    do_mailtester_event POST   /events/:id/do_mailtester(.:format)                               events#do_mailtester
#                       print_list_event GET    /events/:id/print_list(.:format)                                  events#print_list
#                          checkin_event GET    /events/:id/checkin(.:format)                                     events#checkin
#                 send_invitations_event POST   /events/:id/send_invitations(.:format)                            events#send_invitations
#         check_invitations_status_event POST   /events/:id/check_invitations_status(.:format)                    events#check_invitations_status
#                   send_test_mail_event POST   /events/:id/send_test_mail(.:format)                              events#send_test_mail
#                       import_csv_event GET    /events/:id/import_csv(.:format)                                  events#import_csv
#                       export_csv_event GET    /events/:id/export_csv(.:format)                                  events#export_csv
#                    export_failed_event GET    /events/:id/export_failed(.:format)                               events#export_failed
#                    do_import_csv_event POST   /events/:id/do_import_csv(.:format)                               events#do_import_csv
#         send_invitation_event_attendee POST   /events/:event_id/attendees/:id/send_invitation(.:format)         attendees#send_invitation
# check_invitation_status_event_attendee POST   /events/:event_id/attendees/:id/check_invitation_status(.:format) attendees#check_invitation_status
#                  ticket_event_attendee GET    /events/:event_id/attendees/:id/ticket(.:format)                  attendees#ticket
#                    logs_event_attendee GET    /events/:event_id/attendees/:id/logs(.:format)                    attendees#logs
#                 checkin_event_attendee GET    /events/:event_id/attendees/:id/checkin(.:format)                 attendees#checkin
#                        event_attendees GET    /events/:event_id/attendees(.:format)                             attendees#index
#                                        POST   /events/:event_id/attendees(.:format)                             attendees#create
#                     new_event_attendee GET    /events/:event_id/attendees/new(.:format)                         attendees#new
#                    edit_event_attendee GET    /events/:event_id/attendees/:id/edit(.:format)                    attendees#edit
#                         event_attendee GET    /events/:event_id/attendees/:id(.:format)                         attendees#show
#                                        PATCH  /events/:event_id/attendees/:id(.:format)                         attendees#update
#                                        PUT    /events/:event_id/attendees/:id(.:format)                         attendees#update
#                                        DELETE /events/:event_id/attendees/:id(.:format)                         attendees#destroy
#                       event_categories GET    /events/:event_id/categories(.:format)                            categories#index
#                                        POST   /events/:event_id/categories(.:format)                            categories#create
#                     new_event_category GET    /events/:event_id/categories/new(.:format)                        categories#new
#                    edit_event_category GET    /events/:event_id/categories/:id/edit(.:format)                   categories#edit
#                         event_category GET    /events/:event_id/categories/:id(.:format)                        categories#show
#                                        PATCH  /events/:event_id/categories/:id(.:format)                        categories#update
#                                        PUT    /events/:event_id/categories/:id(.:format)                        categories#update
#                                        DELETE /events/:event_id/categories/:id(.:format)                        categories#destroy
#                                 events GET    /events(.:format)                                                 events#index
#                                        POST   /events(.:format)                                                 events#create
#                              new_event GET    /events/new(.:format)                                             events#new
#                             edit_event GET    /events/:id/edit(.:format)                                        events#edit
#                                  event GET    /events/:id(.:format)                                             events#show
#                                        PATCH  /events/:id(.:format)                                             events#update
#                                        PUT    /events/:id(.:format)                                             events#update
#                                        DELETE /events/:id(.:format)                                             events#destroy
#                           mg_delivered POST   /mg/delivered(.:format)                                           mg#webhook
#                             mg_dropped POST   /mg/dropped(.:format)                                             mg#webhook
#                             mg_bounced POST   /mg/bounced(.:format)                                             mg#webhook
#                                  users GET    /users(.:format)                                                  users#index
#                                        POST   /users(.:format)                                                  users#create
#                               new_user GET    /users/new(.:format)                                              users#new
#                              edit_user GET    /users/:id/edit(.:format)                                         users#edit
#                                   user GET    /users/:id(.:format)                                              users#show
#                                        PATCH  /users/:id(.:format)                                              users#update
#                                        PUT    /users/:id(.:format)                                              users#update
#                                        DELETE /users/:id(.:format)                                              users#destroy
#                                   root GET    /                                                                 static#index
#                          configuration GET    /configuration(.:format)                                          static#configuration
#                       example_validate GET    /example_validate(.:format)                                       static#example_validate
#
# Routes for Ckeditor::Engine:
#         pictures GET    /pictures(.:format)             ckeditor/pictures#index
#                  POST   /pictures(.:format)             ckeditor/pictures#create
#          picture DELETE /pictures/:id(.:format)         ckeditor/pictures#destroy
# attachment_files GET    /attachment_files(.:format)     ckeditor/attachment_files#index
#                  POST   /attachment_files(.:format)     ckeditor/attachment_files#create
#  attachment_file DELETE /attachment_files/:id(.:format) ckeditor/attachment_files#destroy
#

Rails.application.routes.draw do
  devise_for :users, skip: [:registration]

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :events do
    member do
      get 'live', as: 'live'
      get 'validate', as: 'validate'
      get 'ticket', as: 'ticket'

      get 'mailtester', as: 'mailtester'
      post 'do_mailtester', as: 'do_mailtester'

      get 'print_list', as: 'print_list'
      get 'checkin', as: 'checkin'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendize</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.full.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.min.css" rel="stylesheet">

  </head>

  <body style="margin-bottom: 2rem">

	  <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">

		  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
		  </button>

		  <%= link_to "Attendize", :root, class: "navbar-brand" %>

		  <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
			  <ul class="navbar-nav mr-auto">
				  <li class="nav-item dropdown">
					  <%= link_to 'Events', events_path, class: "nav-link dropdown-toggle", data: { toggle: "dropdown" } %>
					  <div class="dropdown-menu">
						  <h6 class="dropdown-header">Upcoming events</h6>

						  <% @upcommig_events.each do |event| %>
							  <%= link_to event.name, event_path(event), class: "dropdown-item" %>
						  <% end %>
						  <% unless @upcommig_events.any? %>
							  <a class="dropdown-item text-muted">None</a>
						   <% end %>

						  <div class="dropdown-divider"></div>
					    
						  <%= link_to 'View all', events_path, class: "dropdown-item" %>
						  <%= link_to 'Create', new_event_path, class: "dropdown-item" %>
					  </div>
				  </li>

          <% if current_user.has_role?(:admin) %>
				  <li class="nav-item">
					  <%= link_to 'Users', users_path, class: "nav-link" %>
				  </li>

				  <li class="nav-item">
					  <%= link_to 'Configuration', configuration_path, class: "nav-link" %>
          </li>
          <% end %>
			  </ul>

			  <ul class="navbar-nav">

           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%= current_user.email %>
             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
               <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>  
             </div>
           </li>
        </ul>

         <% end %>
		  </div>
	  </nav>


	  <div class="container-fluid" style="margin-top: 2rem">

      <% if Sidekiq::Stats.new.enqueued > 0 %>
			  <div class="alert alert-warning alert-dismissible fade show" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
				  </button>
				  Sidekiq is still processing background jobs
			  </div>
      <% end %>

		  <% flash.each do |key, value| %>
			  <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
				  </button>
				  <%= value %>
			  </div>
		  <% end %>

		  <%= yield %>
	  </div>
  </body>
</html>